language: python
fast_finish: true

python:
  - 3.6
  - 2.7

os:
  - linux

git:
  depth: 3


install: pip -q install -e .[tests]

script:
  - pytest -v

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then 
    coverage run tests/test_all.py;
    coveralls; 
    fi
